<?php 
//https://cargotsi.mercurygate.net/MercuryGate/common/remoteService.jsp?userid=ProtoWSID&password=ProtoWebSvc2016!;

$oid_value = array(27682980122,27682980122,27683130115,27683519352,27684014987);

$mh = curl_multi_init();

for ($i=0; $i < count($oid_value); $i++) { 
   $request[$i] = '<service-request>
                        <service-id>WebExtractTransportDeep</service-id>
                        <!-- The <request-id> tag is populated with a unique String (generated by caller); This number is used for troubleshooting purposes. -->
                        <request-id>20141204-Test-3</request-id>
                        <data>
                        <!-- The Oid value is found using the OidLookup request. -->
                          <oid>'.$oid_value[$i].'</oid>
                        </data>
                    </service-request>';

                  $params[$i] = array(
                      "userid" => "ProtoWSID",
                      "password" => "ProtoWebSvc2016!",
                      "request" => urlencode($request[$i])
                  );

            foreach ($params[$i] as $k1 => $v1) {
                          $postData[$i] .= $k1 . '=' . $v1 . '&';
                      };
            rtrim($postData[$i], '&');

            $ch_[$i] = curl_init('https://cargotsi.mercurygate.net/MercuryGate/common/remoteService.jsp?');
                curl_setopt($ch_[$i], CURLOPT_RETURNTRANSFER, true);
                curl_setopt($ch_[$i], CURLOPT_POST, count($postData[$i]));
                curl_setopt($ch_[$i], CURLOPT_POSTFIELDS, $postData[$i]);
                curl_multi_add_handle($mh, $ch_[$i]);
}

  
// execute all queries simultaneously, and continue when all are complete
  $running = null;
  do {
    curl_multi_exec($mh, $running);
  } while ($running);

//close the handles
for ($i=0; $i < count($oid_value); $i++) {
    curl_multi_remove_handle($mh, $ch_[$i]);
}

curl_multi_close($mh);
  

for ($i=0; $i < count($oid_value); $i++) {
   $response_[$i] = curl_multi_getcontent($ch_[$i]);
}

$xml_answer = '';
for ($i=0; $i < count($oid_value); $i++) {
  $xml_answer .= base64_decode($response_[$i]);
}

echo $xml_answer;
?>