<?php 
    //$_POST['ref1'];
    $reference_number = $_POST['ref1'];
	$reference_type = $_POST['ref_type'];
	//echo 'Your Reference number is :'.$oidvalue;
	//echo '<br>';
    
    function httpPost($url, $params) {
        $postData = '';
        //create name value pairs seperated by &
        foreach ($params as $k => $v) {
            $postData .= $k . '=' . $v . '&';
        }
        rtrim($postData, '&');

        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_HEADER, false);
        curl_setopt($ch, CURLOPT_POST, count($postData));
        curl_setopt($ch, CURLOPT_POSTFIELDS, $postData);

        $output = curl_exec($ch);

        curl_close($ch);
        return $output;
    }

    if ($reference_type == 'BOL') {
        $request = '<?xml version="1.0"?>
        <!-- Consult the WSDocumentation .docx file for more details on the content of this file. -->
        <service-request>
          <service-id>OidLookup</service-id>
          <!-- The <request-id> tag is populated with a unique String (generated by caller); This number is used for troubleshooting purposes. -->
          <request-id>20160211-Test-1</request-id>
          <data>
            <objectType>transport</objectType>
            <searchBy>primaryReference</searchBy>
            <searchValue>'.$reference_number.'</searchValue>
            <searchModifier/>
          </data>
        </service-request>';
    } else {
	   $request = '<?xml version="1.0"?>
        <!-- Consult the WSDocumentation .docx file for more details on the content of this file. -->
        <service-request>
          <service-id>OidLookup</service-id>
          <!-- The <request-id> tag is populated with a unique String (generated by caller); This number is used for troubleshooting purposes. -->
          <request-id>20141204-Test-1</request-id>
          <data>
            <objectType>transport</objectType>
            <searchBy>reference</searchBy>
            <searchValue>'.$reference_number.'</searchValue>
            <searchModifier>
              <searchBy>'.$reference_type.'</searchBy>     <!-- This is the RefType name to use with searchValue -->
            </searchModifier>
          </data>
        </service-request>';
	};

    $params = array(
        "userid" => "ProtoWSID",
        "password" => "ProtoWebSvc2016!",
        "request" => urlencode($request)
    );

    $xml = httpPost("https://cargotsi.mercurygate.net/MercuryGate/common/remoteService.jsp", $params);


    $response = simplexml_load_string($xml);
	//$decoded64 = base64_decode($response->data);
	//echo 'Your Oid number is :'.$response->data;
	//echo '<br>';
	$oidvalue = $response->data;
	

//-----------------------------------------//---------------
  $oidvalue_split2 = explode(",", $oidvalue);
   $count = 1;
  if(count($oidvalue_split2)>1){
    //echo 'Hello World';

                          //$oid_value = array(27682980122,27682980122,27683130115,27683519352,27684014987);

                          $mh = curl_multi_init();
                          //$oidvalue_split2 = array(27682980122,27682980122,27683130115,27683519352,27684014987);

                          for ($i=0; $i < count($oidvalue_split2); $i++) { 
                             $request2[$i] = '<?xml version="1.0"?>
                                                  <service-request>
                                                    <!-- Please consult the WSDocumentation .doc file for specific details on the contents of this file. -->
                                                    <service-id>ExtractDocuments</service-id>
                                                    <!-- The <request-id> tag is populated with a unique String (generated by you); you can use this number for troubleshooting purposes as needed. -->
                                                    <request-id>20150219</request-id>
                                                    <data>
                                                        <!-- oid of the object that owns the documentType and the desired document type.  -->
                                                        <oid>'.$oidvalue_split2[$i].'</oid>
                                                      <!-- Supported <documentType> values:  Configurable within the TMS. xx|DocTypes| value -->
                                                        <documentType>BOL</documentType>
                                                    </data>
                                                  </service-request>';
                                            $params2[$i] = array(
                                                "userid" => "ProtoWSID",
                                                "password" => "ProtoWebSvc2016!",
                                                "request" => urlencode($request2[$i])
                                            );

                                      foreach ($params2[$i] as $k1 => $v1) {
                                                    $postData2[$i] .= $k1 . '=' . $v1 . '&';
                                                };
                                      rtrim($postData2[$i], '&');

                                          $ch_[$i] = curl_init('https://cargotsi.mercurygate.net/MercuryGate/common/remoteService.jsp?');
                                          curl_setopt($ch_[$i], CURLOPT_RETURNTRANSFER, true);
                                          curl_setopt($ch_[$i], CURLOPT_POST, count($postData2[$i]));
                                          curl_setopt($ch_[$i], CURLOPT_POSTFIELDS, $postData2[$i]);
                                          curl_multi_add_handle($mh, $ch_[$i]);
                          }

                            
                          // execute all queries simultaneously, and continue when all are complete
                            $running = null;
                            do {
                              curl_multi_exec($mh, $running);
                            } while ($running);

                          //close the handles
                          for ($i=0; $i < count($oidvalue_split2); $i++) {
                              curl_multi_remove_handle($mh, $ch_[$i]);
                          }

                          curl_multi_close($mh);
                            

                          for ($i=0; $i < count($oidvalue_split2); $i++) {
                             $response_[$i] = curl_multi_getcontent($ch_[$i]);
                          }

                          $xml_answer = '';
                          for ($i=0; $i < count($oidvalue_split2); $i++) {
                            $xml_answer .= base64_decode($response_[$i]);
                          }

                          echo $xml_answer;
       
  }else{
  

          $request2 = '<service-request>
              <service-id>WebExtractTransportDeep</service-id>
              <!-- The <request-id> tag is populated with a unique String (generated by caller); This number is used for troubleshooting purposes. -->
              <request-id>20141204-Test-3</request-id>
              <data>
              <!-- The Oid value is found using the OidLookup request. -->
                <oid>'.$oidvalue.'</oid>
              </data>
            </service-request>';

          $params2 = array(
                "userid" => "ProtoWSID",
                "password" => "ProtoWebSvc2016!",
                "request" => urlencode($request2)
            );
               
          $xml2 = httpPost("https://cargotsi.mercurygate.net/MercuryGate/common/remoteService.jsp", $params2);
          
          $response2 = simplexml_load_string($xml2);
          $decoded = base64_decode($response2->data);
          //echo '------';
          echo $decoded;
          //echo $xml2;
  }

	
?>